endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

consumed:
  microservice:
    name: "microservice1"
    url: "http://192.168.99.100:8090/" #Change this to whatever your URL is for the consumed microservice
